services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XimaTypo3Manual\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Xima\XimaTypo3Manual\Preview\MtextPreviewRenderer:
    public: true
